version: '3'
services:
  web:
   restart: always
   build: ./web
   expose:
     - "8000"
   depends_on:
     - db
   command: gunicorn test.wsgi -b 0.0.0.0:8000
   volumes:
     - ./web:/usr/src/app
     - ./web/static/:/usr/src/app/static
   env_file:
     - ./envs/db.env
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/:/etc/nginx/"
      - /web/static
    depends_on:
      - web
  db:
   restart: always
   build: ./postgres
   ports:
     - 5432:5432
   volumes:
     - ./postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
     - pgdata:/var/lib/postgresql/data
   env_file:
     - ./envs/db.env
  cli:
    build: ./cli
    depends_on:
      - web
    volumes:
      - ./cli:/usr/src/app
    command: /bin/sh -c "while true; do echo Running Django CLI Tool Container; sleep 600; done"
volumes:
  pgdata:
    driver: "local"