version: '2'
services:
  web:
   restart: always
   build: ./web
   expose:
     - "8000"
   depends_on:
     - db
   command: gunicorn app.wsgi -b 0.0.0.0:8000
   volumes:
     - ./web:/usr/src/app
     - ./web/static/:/usr/src/app/static
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/:/etc/nginx/"
      - /www/static
    volumes_from:
      - web
    links:
      - web:web
  db:
   restart: always
   build: ./postgres
   ports:
     - 5432:5432
   volumes:
     - ./postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
   environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
